version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  tests:
    working_directory: ~/circle
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-base-adapter
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key:  $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "f4:ae:38:63:c0:71:e1:18:ef:44:22:29:3c:00:5a:3a"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_f4ae3863c071e118ef4422293c005a3a" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone -b get-circle-token-from-k8s-secret git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test environment
          environment:
            APPLICATION_NAME: fb-base-adapter
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-base-adapter-test
          command: './deploy-scripts/bin/deploy'
  trigger_acceptance_tests:
    working_directory: ~/circle/git/fb-base-adapter
    docker: *ecr_image
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:ae:38:63:c0:71:e1:18:ef:44:22:29:3c:00:5a:3a"
      - run:
          name: cloning deploy scripts
          command: 'git clone -b get-circle-token-from-k8s-secret git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: "Trigger Acceptance Tests"
          command: './deploy-scripts/bin/acceptance_tests'

workflows:
  version: 2
  release:
    jobs:
      - tests
      - build_and_deploy_to_test:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
                - testing-deployments
                - deploy-to-test
      - trigger_acceptance_tests:
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only:
                - master
                - testing-deployments
